### PR TITLE
Pretty2

### PR DESCRIPTION
**Pull request by Jacob-Gray**

### CODE REVIEW

**Comment by jackmawer** [comment]
Moved from #7.

**Comment by thomas-daniels** [comment]
Live demo: http://fox.montreus.com/demos/TPC/

**Comment by jackmawer** [comment]
@ProgramFOX Thanks. Again, I'm waiting for @Unihedro 's casting vote.

**Comment by Jacob-Gray** [comment]
Well, he usually wakes up if you ping him.... JK :smiling_imp:

**Comment by jackmawer** [comment]
@Unihedro agrees, so pushing it now.

**Pull request merged**
