### PR TITLE
Prettified the webpage

### PR DESCRIPTION
**Pull request by Jacob-Gray**

### CODE REVIEW

**Comment by jackmawer** [comment]
Do you have a live demo of this?

**Comment by thomas-daniels** [comment]
I like this new design! +1

Live demo: http://fox.montreus.com/demos/TPC/

**Comment by jackmawer** [comment]
Postponed for 1 month
Reason: I want to recode the website completely myself, but if I don't do it within a month I'm putting this live, as the current page is a terrible eyesore!

**Comment by thomas-daniels** [comment]
@jackmawer Why can't you put this one live now?

**Comment by jackmawer** [comment]
@ProgramFOX Fine, I'll push it when I've had a comment from @Unihedro .

**Comment by jackmawer** [comment]
Pull request closed.
Reason: Moved to https://github.com/jackmawer/Teenage-Programmers-Website/pull/8

**Pull request closed without merging**
